name: CI - Validar, testar e fazer deploy

on:
  push:
    branches:
      - main
      - feat/**
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm ci

      - name: Verificar ESLint
        run: npx eslint .

      - name: Verificar Prettier
        run: npx prettier --check .

      - name: Build do projeto
        run: npm run build

      - name: Executar testes com Jest
        run: npm test -- --passWithNoTests

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm ci

      - name: Deploy para Netlify
        run: npx netlify-cli deploy --site ${{ secrets.SITE_ID }} --auth ${{ secrets.TOKEN_ID }} --prod
