name: CI - Validar, testar e fazer deploy

on:
  push:
    branches:
      - main
      - feat/**
  pull_request:
    branches:
      - main
  repository_dispatch:
    types: [contentful_update] #Webhook do Contentful
  schedule:
    #atualizar isto depois no fim, antes da entrega
    - cron: '0 0 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # --- Contentful secrets (iguais aos do .env.local)
      CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
      CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
      CONTENTFUL_PREVIEW_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_PREVIEW_ACCESS_TOKEN }}
      CONTENTFUL_PREVIEW_SECRET: ${{ secrets.CONTENTFUL_PREVIEW_SECRET }}
      CONTENTFUL_REVALIDATE_SECRET: ${{ secrets.CONTENTFUL_REVALIDATE_SECRET }}
      # --- Versões públicas (caso o código use NEXT_PUBLIC_*)
      NEXT_PUBLIC_CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
      NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
      NEXT_PUBLIC_CONTENTFUL_PREVIEW_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_PREVIEW_ACCESS_TOKEN }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm ci

      - name: Verificar ESLint
        run: npx eslint .

      - name: Verificar Prettier
        run: npx prettier --check .

      - name: Build do projeto
        run: npm run build

      - name: Executar testes com Jest
        run: npm test -- --passWithNoTests

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    env:
      # --- Netlify secrets
      NETLIFY_SITE_ID: ${{ secrets.SITE_ID }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.TOKEN_ID }}
      # --- Contentful secrets também no deploy (necessários se Netlify rebuildar)
      CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
      CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
      CONTENTFUL_PREVIEW_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_PREVIEW_ACCESS_TOKEN }}
      CONTENTFUL_PREVIEW_SECRET: ${{ secrets.CONTENTFUL_PREVIEW_SECRET }}
      CONTENTFUL_REVALIDATE_SECRET: ${{ secrets.CONTENTFUL_REVALIDATE_SECRET }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm ci

      - name: Deploy para Netlify
        run: npx netlify-cli deploy --site ${{ secrets.SITE_ID }} --auth ${{ secrets.TOKEN_NET }} --prod
